---
  - name: Gather facts before installation
    include_tasks: gather-facts.yml

  - name: Download bun artifact based on facts
    include_tasks: download.yml
  
  - name: Installation multiple versions
    include_tasks: multi.yml
    when: bun_multi_version

  - name: Install single version version
    ansible.builtin.copy:
      src: "/tmp/{{ bun_filename }}/bun"
      dest: "/usr/bin"
      mode: a+x
      force: true
      remote_src: true
    when: not bun_multi_version
  
  - name: Flush assets after installation
    include_tasks: flush.yml